version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: neostore
    restart: always
    ports:
      - "5450:5432"  # Porta local 5450 -> Porta do container 5432
    environment:
      POSTGRES_DB: neostore
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: